export const REGISTER_USER = 'REGISTER_USER';
export const LOGIN_USER = 'LOGIN_USER';
export const USER_CLICK_LOGIN_LABEL = 'USER_CLICK_LOGIN_LABEL';
export const USER_CLICK_LOGOUT_LABEL = 'USER_CLICK_LOGOUT_LABEL';
export const REGISTER_ROUTE = 'REGISTER_ROUTER';
export const LOGIN_ROUTE = 'LOGIN_ROUTE';
export const SEND_FORGOT_PASS_VERIF_CODE_SUCCESS = 'SEND_FORGOT_PASS_VERIF_CODE_SUCCESS';
export const SEND_FORGOT_PASS_VERIF_CODE_ERR = 'SEND_FORGOT_PASS_VERIF_CODE_ERR';
export const SHOW_LOADING_IN_SEND_VERIF_CODE_FORGOT_PASS =
  'SHOW_LOADING_IN_SEND_VERIF_CODE_FORGOT_PASS';
export const SHOW_LOADING_IN_CHECK_VERIF_CODE_FORGOT_PASS =
  'SHOW_LOADING_IN_CHECK_VERIF_CODE_FORGOT_PASS';
export const CHECK_VERI_CODE_FORGOT_PASS_ERR = 'CHECK_VERI_CODE_FORGOT_PASS_ERR';
export const CHECK_VERI_CODE_FORGOT_PASS_SUCCESS = 'CHECK_VERI_CODE_FORGOT_PASS_SUCCESS';
