export const REGISTER_USER = 'REGISTER_USER';
export const LOGIN_USER = 'LOGIN_USER';
export const USER_CLICK_LOGIN_LABEL = 'USER_CLICK_LOGIN_LABEL';
export const USER_CLICK_REGISTER_LABEL = 'USER_CLICK_REGISTER_LABEL';
export const USER_CLICK_LOGOUT_LABEL = 'USER_CLICK_LOGOUT_LABEL';
