# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'kurir' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for kurir

  target 'kurir-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'kurirTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'kurir-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for kurir-tvOS

  target 'kurir-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

pod 'RNVectorIcons', :path => 'node_modules/react-native-vector-icons'
